version: "3.8"

services:
  accomodation_service:
    image: accomodation_service
    container_name: accomodation_service
    hostname: accomodation_service
    build:
      context: ./accomodation-service/
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 9000
      DATABASE_NAME: BOOKING_ACCOMODATION
      STORAGE_URL: https://xcyrzflhnfgpyzfdzalc.supabase.co/storage/v1
      STORAGE_SERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeXJ6ZmxobmZncHl6ZmR6YWxjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4MDYzODU0NSwiZXhwIjoxOTk2MjE0NTQ1fQ.CJURcOscoWrsZ1A0tkCLbjK854YUvvzYRFoO7Q-gRs8
      STORAGE_MAIN_BUCKET: pictures
      DATABASE_CONNECTION_STRING: mongodb+srv://xws:lozinka123@cluster0.yqfgbck.mongodb.net/?retryWrites=true&w=majority
    networks:
      - network
  reservation_service:
    image: reservation_service
    container_name: reservation_service
    hostname: reservation_service
    build:
      context: ./reservation-service/
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 9000
      DATABASE_NAME: BOOKING_RESERVATION
      JWT_SECRET: secret
      DATABASE_CONNECTION_STRING: mongodb+srv://xws:lozinka123@cluster0.yqfgbck.mongodb.net/?retryWrites=true&w=majority
    networks:
      - network
  rating_service:
    image: rating_service
    container_name: rating_service
    hostname: rating_service
    build:
      context: ./rating-service/
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 9000
      DATABASE_NAME: BOOKING_RATING
      JWT_SECRET: secret
      DATABASE_CONNECTION_STRING: mongodb+srv://xws:lozinka123@cluster0.yqfgbck.mongodb.net/?retryWrites=true&w=majority
    networks:
      - network
  auth_service:
    image: auth_service
    container_name: auth_service
    hostname: auth_service
    build:
      context: ./auth-service/
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 9000
      DATABASE_NAME: BOOKING_AUTH
      JWT_SECRET: secret
      DATABASE_CONNECTION_STRING: mongodb+srv://xws:lozinka123@cluster0.yqfgbck.mongodb.net/?retryWrites=true&w=majority
    networks:
      - network

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    hostname: api_gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    restart: always
    environment:
      AUTH_SERVICE_ADDRESS: auth_service:9000
      ACCOMODATION_SERVICE_ADDRESS: accomodation_service:9000
      RESERVATION_SERVICE_ADDRESS: reservation_service:9000
      RATING_SERVICE_ADDRESS: rating_service:9000
      JWT_SECRET: secret
      GATEWAY_ADDRESS: 8085
    depends_on:
      - auth_service
    networks:
      - network
    ports:
      - "8085:8085"

networks:
  network:
    driver: bridge
